{{- $values := .Values.staffPortalUi -}}
{{- if $values.enabled -}}
{{- $context := dict "Values" (merge (deepCopy $values) (dict "global" .Values.global)) "Chart" .Chart "Release" .Release "Files" .Files "Capabilities" .Capabilities -}}
{{- with $context -}}
{{- if and .Values.istio.enabled .Values.istio.virtualservice.enabled }}
{{- $hostname := include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.host "context" $) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
spec:
  hosts:
    - {{ $hostname | quote }}
  gateways:
    - {{ .Values.istio.virtualservice.gateway }}
  http:
    - match:
        - uri:
            prefix: {{ include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.prefix "context" $) }}
      {{- if .Values.istio.virtualservice.rewriteUri }}
      rewrite:
        uri: {{ include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.rewriteUri "context" $) }}
      {{- end }}
      route:
        - destination:
            host: {{ include "common.tplvalues.render" (dict "value" .Values.istio.virtualservice.destination "context" $) }}
            port:
              number: {{ .Values.istio.virtualservice.destinationPort }}
{{- end }}
{{- end -}}
{{- end -}}
